apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wikipedia-article
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fetch
              image: hzd454/fetch-wikipedia-article:latest
          restartPolicy: OnFailure
