apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: todo
spec:
  template:
    spec:
      containers:
        - name: fetch
          image: hzd454/fetch-wikipedia-article:latest
      restartPolicy: Never
