apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-pvc
  namespace: todo
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
