name: Build and release application

on:
  push:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: Build, Push, and Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish image
        run: docker build . -t hzd454/todo-app:$GITHUB_SHA --push

      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: HamzaWahed/dwk-todo-manifests
          token: ${{ secrets.MANIFESTS_REPO_PAT }}
          path: manifests

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag, commit, and push
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          echo $GITHUB_REF
          if [[ "${GITHUB_REF}" = "refs/heads/main" ]]; then
            cd manifests/overlays/staging
            kustomize edit set image PROJECT/IMAGE=hzd454/todo-app:${GITHUB_SHA}
            git add kustomization.yaml
            git commit -m "Update staging image to ${GITHUB_SHA}"
            git push origin
          elif [[ "${GITHUB_REF}" = "refs/tags/*" ]]; then
            cd manifests/overlays/prod
            kustomize edit set image PROJECT/IMAGE=hzd454/todo-app:${GITHUB_SHA}
            git add kustomization.yaml
            git commit -m "Update production image to ${GITHUB_SHA}"
            git push origin
          else
            echo "Not a main branch push or tagged commit. Skipping update."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MANIFESTS_REPO_PAT }}
